### ISSUE TITLE
Error after Home Assistant Core update to version 2021.6.5

### ISSUE THREAD

**Issue by vaclavbalek** [stefanlaheij/ha-buderus#11]
Hello, I am runnind your excellent compponent and many thanks for that. But after na  upgrade to core version 2021.6.5 ha-buderus doesnt work. Sorry for bothering but cou you help please? These are the errors:

Setup failed for buderus: Integration not found.
12:02:38 – (ERROR) setup.py
Platform error: sensor - Integration 'buderus' not found.
12:02:35 – (ERROR) config.py

2021-06-20 12:02:35 ERROR (MainThread) [homeassistant.config] Platform error: sensor - Integration 'buderus' not found.
2021-06-20 12:02:38 ERROR (MainThread) [homeassistant.setup] Setup failed for buderus: Integration not found.

Thank you so much.

**Comment by stefanlaheij** [comment]
Hi,

I recommend you to use this component:
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
Since this component is actively maintained I stopped working on my version.
You can install it through HACS which makes updates also very easy!

Stefan

Op zo 20 jun. 2021 om 12:07 schreef vaclavbalek ***@***.***>:

**Comment by stefanlaheij** [comment]
Hi,

I recommend you to use this component:
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
Since this component is actively maintained I stopped working on my version.
You can install it through HACS which makes updates also very easy!

Stefan
